services:
  nginx:
    image: nginx:1.24-alpine
    container_name: nginx_revprox
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - proxy_network
    depends_on:
      - nginx_react

  nginx_react:
    image: nginx:1.24-alpine
    container_name: nginx_react
    restart: always
    expose:
      - "10309"
    networks:
      - proxy_network

networks:
  proxy_network:
    name: proxy_network
    driver: bridge
