services:
  nginx:
    image: nginx:1.24-alpine
    container_name: nginx_revprox
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - proxy_network

networks:
  proxy_network:
    name: proxy_network
    driver: bridge 